### ISSUE TITLE
出现这个报错我应该怎么办

### ISSUE THREAD

**Issue by HLLF-FAN** [anyshake/observer#21]
![image](https://github.com/user-attachments/assets/b02d1bff-4c40-4b6a-8b8c-20c3d268c9c3)

**Comment by bclswl0827** [comment]
The error is caused by `helicorder`, a new feature introduced in v3.4.0 for generating helicorder images. However, the documentation related to this has not been updated yet.

Please refer to the configuration file located in [build/assets/config.json](https://github.com/anyshake/observer/blob/34293075df5f5fd8f80fb5b425d8760d07f9d780/build/assets/config.json#L82) to implement the merge manually.
